### GET all expenses
GET http://localhost:5186/api/expenses
Accept: application/json


### POST a new expense
POST http://localhost:5186/api/expenses
Content-Type: application/json

{
  "description": "Panaderíaa",
  "amount": 990,
  "date": "2025-05-12T00:00:00",
  "category": "Comidaa"
}


### PUT (update) an expense
PUT http://localhost:5186/api/expenses/1
Content-Type: application/json

{
  "id": 17,
  "description": "papitas ricass",
  "amount": 111,
  "date": "2025-05-12T00:00:00",
  "category": "Food"
}

###

### DELETE an expense
DELETE http://localhost:5186/api/expenses/18